name : Aprendizaje de secuencia de comandos de GitHub

sobre :
   cuestiones :
     tipos : [abierto]

trabajos :
   comentario : se
     ejecuta en : ubuntu-últimos 
    pasos :
      - utiliza : actions/github-script@0.8.0 
        con :
           github-token : $ {{secrets.GITHUB_TOKEN}} 
          script : | 
            github.issues.createComment ({ 
              issue_number: context.issue.number, 
              owner: context.repo.owner, 
              repo: context.repo.repo, 
              body: "🎉 ¡¡¡Has creado este comentario de problema usando GitHub Script !!!" 
            } )
